### PR TITLE
Skip unreadable directories instead of crashing.

### PR DESCRIPTION
**Pull request by tomclegg**

### CODE REVIEW

**Comment by devsnd** [comment]
Hey Tom, thanks for the pull-request!

I think you're the first one to write a test for the pull-request, so I want to congratulate you on that. :tada: 

Unfortunately your test does not like you too much:

> WorldCollapsingException:
> File "/home/travis/build/devsnd/cherrymusic/cherrymusicserver/test/test_cherrymodel.py", line 112
> os.chmod(tmpdir, 0311)

In python3 octal numbers are written `0o311`, which is at least compatible with python 2.7, but I don't know about 2.6... Can you make the change and we'll find out together?

**Comment by tomclegg** [comment]
On it. Learning is fun!

**Comment by devsnd** [comment]
Thanks!

**Comment by tilboerner** [comment]
:+1: Nice work on the test. Great pull request, thanks! :)

**Pull request merged**
