### PR TITLE
Get version from git

### PR DESCRIPTION
**Pull request by MartijnRas**
Heya,

I did some reading up on the best approach to get my changes into separate branches, to get good pull requests.

Cleaning up the mess I made in the devel branch of my fork may still require a hard reset ... I'll decide on that when that turns out to be the only available option.

For know I just wanted to create a pull request for my work on _get_version_from_git.

As it turned the easiest way to create a branch was to:

1) checkout the last commit before I started messing things up (git checkout [commit])
2) creating a branch (git checkout -b [branch])
3) apply and commit the changes
4) push the new branch (git push origin [branch])

In the following three patches  I:
1) Made it check to see if there's a '.git' directory.
2) Replaced the exception handling with flow control.
3) Made it work below Python 3.2. (See: https://github.com/devsnd/cherrymusic/issues/524)

### CODE REVIEW

**Comment by tilboerner** [comment]
Hi Martijn, I made some changes to improve readability and got rid of the separate case for Python >= 3.2, since we don't really need to keep it around. Good job, though, thanks a lot!

**Comment by MartijnRas** [comment]
You might want to update the requirements in the readme file, as it reads Python >= 2.6.

I'm running on Python 2.7 and have not found any compatibility problems except for this method.

**Comment by 6arms1leg** [comment]
Well, 2.7 > 2.6, so it should be compatible. I don't see the problem. :confused:

**Comment by MartijnRas** [comment]
Sorry about my last comment, I misread the commitdiff and failed to notice the workaround for Popen  not having context manager support before Python 3.2.

**Comment by tilboerner** [comment]
No worries! :) The diff makes it look like a huge change, while I really kept almost everything you added. Just moved stuff around and changed some details. ^^

**Pull request merged**
