### PR TITLE
Make username case-insensitive

### PR DESCRIPTION
**Pull request by MaxLeiter**

### CODE REVIEW

**Comment by devsnd** [comment]
Yes, we should make them case insensitive, but before I can accept the PR we also have to make sure that `changePassword`, `addUser` and `deleteUser` are all also case insensitive. Otherwise bad things can happen.

If we're really careful we would check if there any users that would not be able to log in any more in that case (e.g. `devsnd` and `DEVSND`) on startup, but that's probably overkill.

**Comment by MaxLeiter** [comment]
I'll go ahead and put the lowers elsewhere, but this shouldn't stop anyone from logging in -- it just lowercases the username entered and the username it's fetching from the database

**Comment by MaxLeiter** [comment]
Updated, added to changePassword

**Comment by devsnd** [comment]
> I'll go ahead and put the lowers elsewhere, but this shouldn't stop anyone from logging in -- it just lowercases the username entered and the username it's fetching from the database

Well, if anyone would create two users `MAX` and `max` then both could not log in anymore, because of line 108: `assert len(rows) <= 1`. So it's important to make sure that it's impossible to create this scenario by making all accesses lower-cased.

**Comment by MaxLeiter** [comment]
Good point -- done

**Comment by devsnd** [comment]
Thanks, this time you get a dolphin and a fish, so you can feed it.

:dolphin: :fish:

**Pull request merged**
