### PR TITLE
Change TinyTag to mp3info library

### PR DESCRIPTION
**Pull request by andpp**
Tinytag gives wrong playtime with 22050/56Kbit/Mono MP3 audio. mp3info library works perfect and much faster when counting playtime.

### CODE REVIEW

**Comment by devsnd** [comment]
Hi andpp,

Thanks for your pull-request! Unfortunately there are multiple reasons why I cannot accept it:

  #. mp3info is only able to parse mp3 meta info. While tinytag might be slower, tinytag supports mp3, ogg, flac, wav and wma.
  #. tinytag has tests: I cannot tell how good mp3info will work, tinytag however has a nice little test-suite.
  #. You changed core functionality: Even though you might not like the message-of-the-day, you cannot just remove it. It also serves for update-notifications when an admin logs in.

I'd like to encourage you to improve tinytag instead of proposing to replace it. The reason I wrote it is that I couldn't find a small library that can parse multiple formats that works in python 2 and 3.

**Comment by devsnd** [comment]
Hey andpp!

I have taken some time to find out why tinytag was that mauch slower at parsing the tags of mp3s and found out that there is a special header that contains the duration of an mp3 which tinytag previously ignored. TinyTag is now able to parse that so called "Xing"-Header and is speedwise on par with mp3info for files that contain that header. I've already updated tinytag in the devel branch of cherrymusic.

**Comment by andpp** [comment]
Hi Tom,

    Thank you for your reply. Actually It was my first experience with
contribution on GitHub and I made some mistakes and mixed up common
developer branch and branch with changes for my own purposes.

    "Xing"-header used only for VBR MP3 coding. MP3 files with CBR doesn't
have this header. There is another difference between tynytag and mp3info.
TynyTag reads whole file for counting the play time. mp3info reads only a
small part of the file. I can try to port this feature from mp3info to
TinyTag  though I am not sure where should I put my changes - at TinyTag
source git or not. I would appreciate it if you could direct me the right
way.

Andrey Perminov
View my LinkedIn profile <http://www.linkedin.com/in/andreyperminov>
Email: andrey.ppp@gmail.com



2015-10-12 10:05 GMT-07:00 Tom Wallroth <notifications@github.com>:

**Comment by devsnd** [comment]
Hi Andrey,

TinyTag actually only reads the first 30 seconds of a file. If there is no Xing-Header, the average of the bitrates and the total filesize determine a duration estimate. In case of a CBR file, it would be easy to stop after parsing just one frame, because the bitrate does not ever change. Unfortunately we cannot ever be sure if it's VBR or CBR, because the only difference between the two is that there are more than one bitrate in different frames.

Maybe we could add the following ability to TinyTag: If there are e.g. 5 consecutive frames with the same bitrate, we assume it's CBR and stop. This should make TinyTag more accurate for VBR files without Xing-Header without sacrificing too much computational power for CBR files.

Maybe we should continue this discussion over at https://github.com/devsnd/tinytag/issues

**Pull request closed without merging**
