### PR TITLE
Change transcode option choices

### PR DESCRIPTION
**Pull request by Druneau**
-Change transcode option formatting to show bitrate instead of Low/Medium tags.

-Added transcode bitrate 320kbps

### CODE REVIEW

**Comment by devsnd** [comment]
Hi Druneau,

Thanks for your Pull-Request! Personally I think that showing a description of the transcoding quality is valuable for not so tech-savvy users.

So could you please change it to `Low (96 kbit/s)`, `Medium (128 kbit/s)`, `Very High (320 kbit/s)`, before I merge?

**Comment by Druneau** [comment]
In that case I might put the disabled input box back in to show the resulting bitrate that will be applied upon choosing one of either Low, Medium or Very High?  Or should I write it exactly like you did, `Description (bitrate)`

Initially I was going to just add the `High` tag, but that resulted in things going multi-line... so I had switched to showing bitrate only and that fit nicely (removing the input box that became redundant)

I do agree a description of the chosen bitrate is more user friendly.  Initially I was going to try and add a way for the user to specify his Low/Medium in the cherrymusic config, but I wussed out and only added the 320kbps option..

**Comment by tilboerner** [comment]
> Initially I was going to try and add a way for the user to specify his Low/Medium in the cherrymusic config, but I wussed out and only added the 320kbps option..

Good. As someone who needs to keep an eye on an over-engineering habit, I commend your restraint. :) Simply adding a sensible option is the way to go here. (There's a point to be made about giving the server admin a say in this matter, but until somebody makes it...)

> In that case I might put the disabled input box back in to show the resulting bitrate that will be applied upon choosing one of either Low, Medium or Very High?

My favored solution, because I think it's easier on the eye. It also emphasizes the relative aspect, *low* vs. *high*, over the actual bitrates, leaving some wiggle room for change and reinterpretation. That's why it ended up looking like it did, anyway. :eyes: 

If space becomes an issue, I recommend turning the checkboxes into a `<select>`. I'd still keep the disabled input box in this case, or experiment with a low-key `<span>` of text.

**Comment by tilboerner** [comment]
Sorry, didn't even notice the commit was up already. Great, thank you! :+1:

**Comment by Druneau** [comment]
Yeah, my skills aren't there yet for changing it into a `<select>`.  I might give it a go when I have some free time.  So for now I simply added the `Very High` bitrate I wanted to use.  (I've been manually patching it on my server every release... haha)

Thanks for cherrymusic.  I've been using it for at least a year, almost every workday.

**Comment by tilboerner** [comment]
@Druneau: No worries, and thanks again! 

I replaced the radio buttons with a `<select>` element. If you're curious how it was done, have a look at commit 28140ca9f02e879fbf884ca698b982b9d3610d70.

**Pull request merged**
