### PR TITLE
Fix a typo in error message

### PR DESCRIPTION
**Pull request by rtaibah**

### CODE REVIEW

**Comment by devsnd** [comment]
Thanks Rami!

**Comment by devsnd** [comment]
:camel:

**Comment by tilboerner** [comment]
& :cake:

**Comment by rtaibah** [comment]
Wow camel and cake. I did nothing really, the typo just bugged me. Hopefully there will be further contributions that can be more meaningful.

**Comment by tilboerner** [comment]
> I did nothing really, the typo just bugged me.

And now it's fixed. Little things count! Thanks. :)

**Pull request merged**
