### PR TITLE
Patch to make clear also stop playback and clear interface

### PR DESCRIPTION
**Pull request by MartijnRas**
Hello,

Pressing \clear' currently only clears the play list, where I'd expected it to also stop playback.

I started by adding a call to cmd_stop in clearQueue, which stopped playback but left the title of the page and player unchanged. Both page and player kept displaying the title of the song, the player also kept displaying the length of the song.

Digging through the code and documentation I found the following solution to make pressing 'clear' work as I'd expected.

Mazzel,

Martijn.

### CODE REVIEW

**Comment by MartijnRas** [comment]
I did not know github puts all commits into an open pull request.

The last two commits in my fork belong to the following issue, for which I wanted to open a separate pull request: https://github.com/devsnd/cherrymusic/issues/524

**Comment by tilboerner** [comment]
Hi Martijn, 

> I did not know github puts all commits into an open pull request.

A pull request becomes associated with the branch you start it from. This allows the pull request to be amended with further changes before it gets merged. Think of it as a separate branch where a feature is developed and then merged back when it's ready. So, in general it's a good idea to start a pull request from its own dedicated branch.

Anyway, thanks a lot for putting in the work, it's very much appreciated!

I'd say we leave it like it is for now and discuss the issues separately in their respective tickets. We can decide later if and how we need to sort this out.

However, if you'd like to do further work in your fork in the meantime, it's best if you close this pull request and open two new, separate ones. Let me know if you want to do that, I can give you some pointers on how to cleanly separate your commits into two independent branches.

**Comment by tilboerner** [comment]
Hey other folks,

> Pressing \clear' currently only clears the play list, where I'd expected it to also stop playback.

How do you feel about this? I like having the player continue until I've found something else to put in the queue, so personally I never thought of this behavior as a problem.

In general, the player does not stop if the currenly playing track is removed from the queue or the playing playlist, or if a playing playlist is closed. So, however the player reacts to these events, I think it should do so consistently. No?

cc: @devsnd, @6arms1leg

**Comment by 6arms1leg** [comment]
Remember this?: #124. :older_man: 
That's still my opinion.

**Comment by tilboerner** [comment]
Oh boy, we went through this already? @6arms1leg, thanks for reminding me. Seems like we never really reached a conclusion, too!

For reference, your point from back then:
> nothing in the queue => nothing is played. thats the expected behavior.

Maybe. It depends on your mental model of how playlists relate to the player. Are playlists an active, integral part of the player, or are they just a place to fetch the next song from? The client is built the second way, and behaves like it. But it could do a better job of communicating that "model". Or maybe the other way is superior? I don't know. There seems to be cause to do *something*. I'd just like the behavior to be consistent across all possible playlist events. If we merge this, we should also change how the player reacts in other cases. The question is, should we?

**Comment by devsnd** [comment]
Hey Martijn!

Thanks for your contribution! :cake: 

But I have to admit, that I am already used to the current behavior: I create playlists in the queue and when I clear it, the song keeps playing and I can fill the queue with more tracks. Maybe we should make this behavior optional (especially since people seem have strong feelings about this :racehorse: ).

Could you please add another option in the options panel and only use this behavior if the user decided to do so (opt-in)? If you put that in another pull request, I'd be happy to merge it.

I havent yet looked closely into the git-version-thingy, but I have to agree to @tilboerner that yet another configuration does not make cherrymusic more discoverable. Instead of being able to activate and deactivate the feature using the configuration, just check if there is a `.git` folder. This makes it straight forward instead of introducing more config-options.

**Comment by MartijnRas** [comment]
I will make two separate pull requests for ... closing this one.

**Comment by tilboerner** [comment]
@MartijnRas, to get a clean commit tree at this point it's probably best to start over: make a copy of your work and *reset --hard* your devel branch to the state before your changes. Then make two new branches, copy your saved files into each and selectively commit the right changes (see *add --interactive*). This will give us something we can consider to merge.

Only do this if nobody else is working with your devel branch. You will need to *push -f* to get this on github. Also, be careful with the hard reset, it can be tricky to undo. If you're not sure how these commands work, better read up on them first. :)

**Pull request closed without merging**
