### PR TITLE
Fix logout

### PR DESCRIPTION
**Pull request by faircopy**
Clicking on "Logout" button didn't log me out.

Testing environment:
* Python 3.6.3
* CherryPy 11.0.0
* Firefox 55.0.3, Firefox 56

### CODE REVIEW

**Comment by devsnd** [comment]
Hey @faircopy, thanks for your PR, it's really appreciated! Before I merge it, can you please clear all the session variables that are set in `session_auth`.

https://github.com/faircopy/cherrymusic/blob/86adbd11d0f5af9a96f88d8c71a058239675946e/cherrymusicserver/httphandler.py#L217-L219

Otherwise the logout action is not exactly the reverse of the login action (and there is a stale `user_id` and `isadmin` in the session, which might lead to security issues).

**Comment by faircopy** [comment]
Fixed, I'll be more thorough next time.

**Comment by devsnd** [comment]
@faircopy thanks a bunch! see you next time.
Here, take this sushi as a reward: 🍣

**Comment by faircopy** [comment]
Thanks! :smile:

**Pull request merged**
