### PR TITLE
Rewrite HTTPRedirects so that they use relative URLs

### PR DESCRIPTION
**Pull request by bradchristensen**
The cherrypy HTTPRedirect class automatically converts relative URLs into absolute URLs by prepending a base path, but the base path isn't the host/port requested by the browser, so in doing so, the absolute URL may be incorrect or inconsistent, e.g. if CherryMusic is behind a proxy.

I was hoping there'd be an obvious alternative redirect method/parameters to prevent it from resolving the path but I couldn't find anything, so I came up with a quick and hacky fix instead to start a dialogue about the issue. I won't be upset if you don't want to merge this :)

(it's possible this is also an issue for other instances where HTTPRedirects are used - these are just the only requests I noticed were failing in the browser console)

### CODE REVIEW

**Comment by devsnd** [comment]
Hi Brad,

Thanks for your pull request! I found your fix interesting so I dove into the cherrypy code to find out whats going on and why your fix does indeed work... but, as you mentioned, your fix is quite hackish, so I'd rather not pull it. 

But I have two suggestions for now: 

1. Can you please try to configure the `server.rootpath` in the cherrymusic.conf according to your proxy settings to see if that resolves your issue? (This will probably only work if your proxy serves on the same port as CM, but I'm not sure)

2. There is a cherrypy configuration called `tools.proxy` that should be able to take care of this issue (including serving on another port). So if the `rootpath` config does not do the job for you, we'll have to make the 'tools.proxy' setting of cherrypy configurable in the cherrymusic.conf to resolve this issue properly. (you can try this out by modifying the cherrypy configuration in `cherrymusicserver.__init__.py` around line 480)

Thanks again for contributing to CM! :elephant:

**Comment by polyphenolic** [comment]
Thanks Tom, great to get your feedback!

I just found that this was brought up quiiiite some time ago as an issue with cherrypy (https://bitbucket.org/cherrypy/cherrypy/issue/702/httpredirect-absolute-urls-break-proxied) and they gave the same suggestion - to use tools.proxy - but I feel as if that's only a workaround for the issue being that cherrypy tries to resolve all relative paths into absolute ones, when in this case I would think it'd make more sense for the relative path to be resolved by the browser based on the URL that was actually requested.

Disregarding for a moment the hurdle of implementing it, is there more fundamentally a problem with providing only a relative path to the client that makes it preferable to use absolute URLs instead? It just seems odd to me that cherrypy would enforce it, since relative paths are fine according to the spec.

**Comment by polyphenolic** [comment]
Oh... only as of June 2014 apparently, which would explain why it wasn't allowed previously (http://stackoverflow.com/a/25643550).

**Comment by devsnd** [comment]
It seems CherryPy does not solve the issue in any newer version either. I'm really hesitant to include your solution, even though, as SO shows, it's the correct behavior.

I [opened an issue over at CherryPy](https://bitbucket.org/cherrypy/cherrypy/issue/1355/allow-relative-urls-in-httpredirect), so lets see what they say and decide then how to do it.

**Pull request closed without merging**
